[package]
name = "phantom-networking"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
phantom-core = { path = "../phantom-core" }
phantom-crypto = { path = "../phantom-crypto" }
tokio = { workspace = true }
anyhow = { workspace = true }
libp2p = { workspace = true }
tracing = { workspace = true }
